import type { TutorialStep } from './types';

/**
 * Full-product tour covering every routed page and major feature.
 * Steps navigate automatically; missing selectors are skipped at runtime.
 */
export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    route: '/',
    title: 'Welcome to Nexus',
    body: 'A quick tour of your business operations suite — leads, quotes, proposals, notes, packages, and apps.',
    placement: 'center',
  },
  {
    id: 'home-brand',
    route: '/',
    selector: '[data-tour="home-brand"]',
    title: 'Your workspace brand',
    body: 'Every page opens with the Nexus identity on the navy kaleidoscope panel — your home base.',
    placement: 'right',
    padding: 10,
  },
  {
    id: 'home-nav',
    route: '/',
    selector: '[data-tour="panel-nav"]',
    title: 'Panel navigation',
    body: 'Jump between Home, Leads, Progress Notes, Quote Builder, Proposal Doc, and Bespoke from any left panel.',
    placement: 'bottom',
    padding: 8,
  },
  {
    id: 'home-search',
    route: '/',
    selector: '[data-tour="home-search"]',
    title: 'Quick search',
    body: 'Use the search bar on the light panel to find your way around Nexus.',
    placement: 'bottom',
  },
  {
    id: 'home-cards',
    route: '/',
    selector: '[data-tour="home-nav-grid"]',
    title: 'Navigate to anything',
    body: 'These cards are shortcuts into every major area of the suite. Click one — or follow the tour.',
    placement: 'left',
    padding: 12,
  },
  {
    id: 'leads-intro',
    route: '/leads',
    selector: '[data-tour="leads-tabs"]',
    title: 'Leads pipeline tabs',
    body: 'Filter leads by Live, Booked, Dead, or Blacklisted. Counts update as records load.',
    placement: 'bottom',
    settleMs: 400,
  },
  {
    id: 'leads-search',
    route: '/leads',
    selector: '[data-tour="leads-search"]',
    title: 'Find a lead fast',
    body: 'Search by name, email, company, source, or role to narrow the list.',
    placement: 'bottom',
  },
  {
    id: 'leads-list',
    route: '/leads',
    selector: '[data-tour="leads-list"]',
    title: 'Your lead database',
    body: 'Open any lead to view contact details, assign a rep, call, email, or start a quote.',
    placement: 'left',
    padding: 10,
  },
  {
    id: 'leads-timeline',
    route: '/leads',
    selector: '[data-tour="leads-timeline-btn"]',
    title: 'Pipeline timeline',
    body: 'The ⋮ control opens the five-step booking timeline — from Lead Received through Job Confirmed.',
    placement: 'left',
    padding: 8,
  },
  {
    id: 'leads-fab',
    route: '/leads',
    selector: '[data-tour="leads-fab"]',
    title: 'Add a lead',
    body: 'Use the floating action button when you need to capture someone new into the pipeline.',
    placement: 'left',
    padding: 6,
  },
  {
    id: 'quote-mode',
    route: '/quote-builder',
    selector: '[data-tour="quote-mode"]',
    title: 'Quote Builder modes',
    body: 'Switch between building a fresh quote and reviewing quotes you have already generated.',
    placement: 'bottom',
    settleMs: 350,
  },
  {
    id: 'quote-wizard',
    route: '/quote-builder',
    selector: '[data-tour="quote-wizard"]',
    title: 'Six-step quote wizard',
    body: 'Walk through event core, guests, schedule (with the itinerary watch), catering, financials, and upgrades — then generate a proposal PDF.',
    placement: 'left',
    padding: 12,
  },
  {
    id: 'proposals',
    route: '/proposal-doc',
    selector: '[data-tour="proposal-grid"]',
    title: 'Proposal documents',
    body: 'Open, star, download, share, edit, or delete generated proposals. New quotes land here automatically.',
    placement: 'left',
    settleMs: 350,
    padding: 12,
  },
  {
    id: 'proposals-search',
    route: '/proposal-doc',
    selector: '[data-tour="proposal-search"]',
    title: 'Find a proposal',
    body: 'Search your document library when you need a specific quote pack quickly.',
    placement: 'bottom',
  },
  {
    id: 'notes-mode',
    route: '/progress-notes',
    selector: '[data-tour="notes-mode"]',
    title: 'Notes & status',
    body: 'Toggle between Progress Notes and Status. Notes auto-tag into categories as you type.',
    placement: 'bottom',
    settleMs: 350,
  },
  {
    id: 'notes-list',
    route: '/progress-notes',
    selector: '[data-tour="notes-list"]',
    title: 'Sales workflow notes',
    body: 'Browse all notes or filter to the active lead. Select a note to expand the detail carousel.',
    placement: 'left',
    padding: 10,
  },
  {
    id: 'notes-fab',
    route: '/progress-notes',
    selector: '[data-tour="notes-fab"]',
    title: 'Add a progress note',
    body: 'Capture a note for the active lead — keyword detection files it into the right category.',
    placement: 'left',
  },
  {
    id: 'bespoke',
    route: '/bespoke',
    selector: '[data-tour="bespoke-grid"]',
    title: 'Bespoke packages',
    body: 'Browse curated event packages — Private Charter, Corporate, Celebration, Wedding, Team, and Gala.',
    placement: 'left',
    settleMs: 350,
    padding: 12,
  },
  {
    id: 'bespoke-search',
    route: '/bespoke',
    selector: '[data-tour="bespoke-search"]',
    title: 'Filter packages',
    body: 'Search packages by name or description, then open a card for highlights and enquire.',
    placement: 'bottom',
  },
  {
    id: 'apps',
    route: '/apps',
    selector: '[data-tour="apps-grid"]',
    title: 'Connected apps',
    body: 'Launch Gmail, Drive, WhatsApp, Slack, LinkedIn, and more — links contextualise around your active lead.',
    placement: 'top',
    settleMs: 350,
    padding: 14,
  },
  {
    id: 'tour-restart',
    route: '/',
    selector: '[data-tour="tour-trigger"]',
    title: 'Replay anytime',
    body: 'Restart this tour from the Tour control in the panel nav whenever you need a refresher. You are ready to work.',
    placement: 'bottom',
    settleMs: 300,
  },
];

export const TUTORIAL_STORAGE_KEY = 'nexus_tutorial_done';
